services:
  - type: web
    name: saathi-ml-service
    env: docker
    region: oregon
    plan: free
    rootDir: backend/ml-service
    dockerfilePath: Dockerfile

  - type: web
    name: saathi-api-server
    env: docker
    region: oregon
    plan: free
    rootDir: backend/api-server
    dockerfilePath: Dockerfile
    envVars:
      - key: ML_SERVICE_URL
        value: http://saathi-ml-service:10000
